sudo: required
language: generic

services:
  - docker

before_install:
  # Build the Docker image
  - docker build -t nimroda/docker-react -f Dockerfile.dev .

script:
  - docker run -d --name docker-react-container nimroda/docker-react
# Run tests inside the container, ensuring CI=true is set
  - docker run -d --name docker-react-container nimroda/docker-react

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-122610503598"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
