sudo: required
language: generic

services:
  - docker

before_install:
  # Build the Docker image
  - docker build -t nimroda/docker-react -f Dockerfile.dev .
  
  # Start the container in detached mode
  - docker run -d --name container nimroda/docker-react bash -c "
      apk update && 
      apk add --no-cache bash libxml2-dev libxslt-dev zlib-dev libressl-dev ruby ruby-dev build-base && 
      echo 'Dependencies installed successfully!'"

  # Wait for the container to be ready before running further commands
  - docker exec container sh -c "while ! ps aux | grep -q 'ruby'; do sleep 1; done"

  # Install nokogiri gem inside the Docker container
  - docker exec container gem install nokogiri --platform=ruby

script:
  - docker run -e CI=true nimroda/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-122610503598"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"