sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nimroda/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nimroda/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-122610503598"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY
