sudo: required
language: generic

services:
  - docker

before_install:
  # Build the Docker image
  - docker build -t nimroda/docker-react -f Dockerfile.dev .
  
  # Install glibc 2.28 inside the Docker container
  - docker run -d --name container nimroda/docker-react bash -c "
      apt-get update && 
      apt-get install -y build-essential wget && 
      wget http://ftp.gnu.org/gnu/libc/glibc-2.28.tar.gz && 
      tar -xvzf glibc-2.28.tar.gz && 
      cd glibc-2.28 && 
      mkdir build && 
      cd build && 
      ../configure --prefix=/opt/glibc-2.28 && 
      make -j$(nproc) && 
      sudo make install && 
      export LD_LIBRARY_PATH=/opt/glibc-2.28/lib:$LD_LIBRARY_PATH && 
      exit"

  # Install Nokogiri with the Ruby platform option (to avoid glibc version mismatch)
  - docker run --rm nimroda/docker-react bash -c "
      gem install nokogiri --platform=ruby"

script:
  - docker run -e CI=true nimroda/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-122610503598"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"