sudo: required
language: generic

services:
  - docker

before_install:
  # Build the Docker image
  - docker build -t nimroda/docker-react -f Dockerfile.dev .
  
  # Start the container in detached mode
  - docker run -d --name container nimroda/docker-react bash -c "
      apk update && 
      apk add --no-cache bash libxml2-dev libxslt-dev zlib-dev libressl-dev ruby ruby-dev build-base && 
      echo 'Dependencies installed successfully!' &&
      sleep 3600"  # Use a long-running sleep to ensure the container stays alive

  # Check if the container is running
  - docker ps -a  # This should show the container as "Up"

  # Give the container some time to initialize (10 seconds)
  - sleep 10

  # Check if the container is running
  - docker ps -a  # This will show the status of the container

  # Check logs if the container is not running
  - docker logs container || echo "Failed to retrieve logs"  # Get container logs if it failed

  # If the container is running, proceed with the gem installation
  - docker exec container gem install nokogiri --platform=ruby || (echo "Nokogiri installation failed!" && exit 1)

script:
  - docker run -e CI=true nimroda/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-122610503598"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"